# Data
intermediate_functions: ["a_mod_29", "b_mod_31"]
mod: 113
train_frac: .25
data_seed: 0
multitask: False
n_positions: 3

# Model
n_layer: 1
n_head: 4
n_embd: 128
n_inner: 512

# Training
lr_list: [.001]
model_seed_list: [0]
wd: 1.
betas: [0.9, 0.98]
num_epochs: 100000
checkpoint_every: 1000
save_checkpoints: [1000, 5000, 10000, 25000, 50000, 75000, 100000]

# Output
data_dir: "../data/Two_Nodes/amod29_bmod31"
save_models: True
model_dir: "../Model/Algorithmic_Train/Two_Nodes/amod29_bmod31"
results_dir: "../Results/Algorithmic_Train/Two_Nodes/amod29_bmod31"
