agreement: false
batch_size_list:
- 500
data_seed: 0
gif: false
gif_interval: 10
l0_lambda: 1.0e-06
layer_reinit: false
lm_eval: true
lr_list:
- 0.001
mask_init_list:
- 1.0
max_temp: 200
model_dir: ../Model/Probes/Two_Nodes/amod29_bmod31/B/Full/4999
model_path: ../Model/Algorithmic_Train/Two_Nodes/amod29_bmod31/b2793434-2414-488c-bf83-33afed4b7df0_4999
model_seed_list:
- 0
multitask: false
num_epochs: 0
num_random_ablations: 0
operation_list:
- attn
- mlp
probe_index_list:
- 0
- 1
- 2
random_init: false
results_dir: ../Results/Probes/Two_Nodes/amod29_bmod31/B/Full/4999
save_models: true
target_layer_list:
- 0
test_data_path: ../data/Two_Nodes/amod29_bmod31/test.csv
train_data_path: ../data/Two_Nodes/amod29_bmod31/train.csv
train_size: 3000
variable: var_1
