# Model
model_path: "gpt2"
random_init: False
layer_reinit: False
target_layer_list: [0]
operation_list: ["mlp"]
mask_init_list: [0.0]
max_temp: 200
probe_index_list: [-1]

# Data
data_path: "../data/Reflexive_An/Reflexive_An.csv"
gen_path: "../data/Reflexive_An/Reflexive_An_gen.csv"
train_size: 2000
test_size: 1000
task: "reflexive"

# Training
num_epochs: 90
lr_list: [0.001]
batch_size_list: [500]
data_seed: 0
l0_lambda: 1.0e-07
model_seed_list: [0]

num_random_ablations: 5
lm_eval: True

# Output
model_dir: "../Model/Probes/Reflexive_An/small-save/"
results_dir: "../Results/Probes/Reflexive_An/small-save/"
save_models: True
gif: False