# Model
model_type: "gpt2"
model_path: "gpt2"
random_init: False
target_layer_list: [0]
mask_bias: False
mask_init_list: [0.0]
max_temp: 200

# Data
train_data_path: "../data/ud-treebanks-conll2017/UD_English/en-ud-train.conllu"
lm_data_path: "../data/ud-treebanks-conll2017/UD_English/en-ud-train.conllu"
label: "tag"
train_size: 1000
dev_size: 64
test_size: 64
lm_size: 64

# Training
num_epochs: 3
lr_list: [0.001]
batch_size_list: [4]
seed: 0
l0_lambda: 0.0000001
lm_eval: True

# Output
model_dir: "../Models/gpt-test"
results_dir: "../Results/GPT2/gpt-test"
save_models: False