# Data
counterfactual_label: ["CF_Label_3"]
model_path: "../Model/Algorithmic_Train/Disambiguation/a2_minus_b2_1_layer/model_LR_0.001_Seed_0_final"

data_seed: 0
target_layer_list: [0]
target_position_list: [2]
residual_location_list: ["resid_mid", "resid_post"]

# Output
data_path: "../data/Disambiguation/a2_minus_b2/test.csv"
results_dir: "../Results/Probes/Disambiguation/a2_minus_b2/Interchange/1_layer/cf_label_3"
