batch_size_list:
- 500
counterfactual_embeddings: false
data_seed: 0
intermediate_size: -1
layer_reinit: false
lr_list:
- 0.1
model_path: ../Model/Algorithmic_Train/Grokking/a2_b/model_LR_0.001_Seed_0_7000
model_seed_list:
- 0
n_classes: 113
num_epochs: 100
random_init: false
residual_location_list:
- resid_mid
- resid_post
results_dir: ../Results/Probes/Grokking/a2_b/Probing/Linear/b2/7000
target_layer_list:
- 0
target_position_list:
- 2
test_data_path: ../data/Grokking/a2_b/test.csv
train_data_path: ../data/Grokking/a2_b/train.csv
variable: aux_0
