# Data
intermediate_functions: [["a_plus_b", 0, 1]]
mod: 113
train_frac: .6
data_seed: 0
multitask: False
n_positions: 3

# Model
n_layer: 1
n_head: 4
n_embd: 128
n_inner: 512
model_path: "../Model/Algorithmic_Train/Disambiguation/a2_minus_b2_1_layer/model_LR_0.001_Seed_0_final"

# Training
transfer: true
lr_list: [.001]
model_seed_list: [0]
wd: 1.
betas: [0.9, 0.98]
num_epochs: 450
checkpoint_every: 1
save_checkpoints: [450]

# Output
data_dir: "../data/Disambiguation/Transfer/a_plus_b_1_layer"
save_models: False
model_dir: "../Model/Algorithmic_Train/Disambiguation/Transfer/1_layer/a_plus_b"
results_dir: "../Results/Algorithmic_Train/Disambiguation/Transfer/1_layer/a_plus_b"
figtitle: "a + b"