# Model
model_path: "../Model/Algorithmic_Train/Grokking/a4_b/7a471893-ce32-49a9-96d7-6dab38522e33"
random_init: False
layer_reinit: False
target_layer_list: [0]
operation_list: ["attn", "mlp"]
mask_init_list: [0.0]
max_temp: 200

# Data
train_data_path: "../data/Grokking/a4_b/train.csv"
test_data_path: "../data/Grokking/a4_b/test.csv"
variable: "var_0"
probe_index_list: [2]
train_size: 2500
multitask: False
agreement: False

# Training
num_epochs: 90
lr_list: [0.001]
batch_size_list: [500]
data_seed: 0
model_seed_list: [0]
l0_lambda: 0.000001

num_random_ablations: 0
lm_eval: True

# Output
model_dir: "../Model/Probes/Grokking/a4_b/Mask/"
results_dir: "../Results/Probes/Grokking/a4_b/Mask/"
save_models: False

# GIF
gif: True
gif_interval: 10