data_seed: 0
layer_reinit: false
model_path: "../Model/Algorithmic_Train/Grokking/model_LR_0.001_Seed_0"
model_seed_list:
- 0
residual_location_list: ["resid_mid", "resid_post"]
target_position_list: [2]
random_init: false
results_dir: "../Results/Probes/Grokking/Amnesic/a2/"
target_layer_list: [0]
train_data_path: "../data/Grokking/train.csv"
test_data_path: "../data/Grokking/test.csv"
variable: var_0
n_classes: 113
