# Data
counterfactual_label: "CF_Label_0"
model_path: "../Model/Algorithmic_Train/Disambiguation/model_LR_0.001_Seed_0_final"
n_train: 2500
n_val: 1000

# Intervention
epochs: 250
location_list: ["attn", "mlp"]
token_range: "2_3"

# Output
train_path: "../data/Disambiguation/train.csv"
test_path: "../data/Disambiguation/test.csv"

results_dir: "../Results/Probes/Disambiguation/DAS/cf_label_0"