# Model
model_path: "../Model/Algorithmic_Train/Grokking/a2_b/model_LR_0.001_Seed_0"
random_init: False
layer_reinit: False
target_layer_list: [0]
operation_list: ["attn", "mlp"]
mask_init_list: [0.0]
max_temp: 200

# Data
train_data_path: "../data/Grokking/a2_b/train.csv"
test_data_path: "../data/Grokking/a2_b/test.csv"
variable: "var_0"
probe_index_list: [2]
train_size: 2500
task: grokking

# Training
num_epochs: 90
lr_list: [0.001]
batch_size_list: [500]
data_seed: 0
model_seed_list: [0]
l0_lambda: 0.000001

num_random_ablations: 0
lm_eval: True

# Output
model_dir: "../Model/Probes/Grokking/a2_b/circuit_probing/a2/"
results_dir: "../Results/Probes/Grokking/a2_b/circuit_probing/a2/"
save_models: False

# GIF
gif: True
gif_interval: 10