batch_size_list:
- 500
data_seed: 0
layer_reinit: false
lr_list:
- 0.1
model_path: ../Model/Algorithmic_Train/Grokking/a2_b/568e7cac-54d6-4f6e-a4fc-2065f0a8debe_1999
model_seed_list:
- 0
n_classes: 113
num_epochs: 500
operation_list:
- attn
- mlp
probe_index_list:
- 2
random_init: false
results_dir: ../Results/Probes/Grokking/a2_b/Probe/b2/1999
target_layer_list:
- 0
test_data_path: ../data/Grokking/a2_b/test.csv
train_data_path: ../data/Grokking/a2_b/train.csv
variable: aux_0
