# Data
counterfactual_label: "CF_Label_3"
model_path: "../Model/Algorithmic_Train/Disambiguation/a2_minus_b2_1_layer/model_LR_0.001_Seed_0_final"
n_train: 2500
n_val: 1000

# Intervention
epochs: 250
location_list: ["attn", "mlp"]
token_range: "2_3"

# Output
train_path: "../data/Disambiguation/a2_minus_b2/train.csv"
test_path: "../data/Disambiguation/a2_minus_b2/test.csv"

results_dir: "../Results/Probes/Disambiguation/a2_minus_b2/DAS/1_layer/cf_label_3"