data_seed: 0
layer_reinit: false
model_path: ../Model/Algorithmic_Train/Disambiguation/model_LR_0.001_Seed_0_final
residual_location_list: ["resid_mid", "resid_post"]
target_position_list: [2]
model_seed_list: [0]
random_init: false
results_dir: ../Results/Probes/Disambiguation/Amnesic/a2/
target_layer_list: [0]
test_data_path: ../data/Disambiguation/test.csv
train_data_path: ../data/Disambiguation/train.csv
variable: var_0
n_classes: 113
