# Model
model_type: "mpnet"
model_path: "microsoft/mpnet-base"
random_init: False
target_layer_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
mask_bias: False
mask_init_list: [0.0]
max_temp: 200

# Data
train_data_path: "../data/ud-treebanks-conll2017/UD_English/en-ud-train.conllu"
lm_data_path: "../data/ud-treebanks-conll2017/UD_English/en-ud-dev.conllu"
label: "pos"
train_size: 1000
dev_size: 100
test_size: 1000
lm_size: 100

# Training
num_epochs: 90
lr_list: [0.001]
batch_size_list: [16]
seed: 0
l0_lambda: 0.0000001
lm_eval: True

# Output
model_dir: "../Models/pos"
results_dir: "../Results/MPNet/Pos/pos"
save_models: False