# Data
multitask: True
intermediate_functions_1: ["a_mod_29", "b_mod_31"]
intermediate_functions_2: ["a_mod_29", "b_mod_23"]
mod: 113
train_frac: .5
data_seed: 0

# Model
n_layer: 1
n_head: 4
n_embd: 128
n_inner: 512
n_positions: 4

# Training
lr_list: [.001]
model_seed_list: [0]
wd: 1.
betas: [0.9, 0.98]
num_epochs: 50000
checkpoint_every: 5000
save_checkpoints: [5000, 10000, 20000, 30000, 40000, 50000]
transfer: False

# Output
data_dir: "../data/Shared_Nodes"
save_models: True
model_dir: "../Model/Algorithmic_Train/Shared_Nodes"
results_dir: "../Results/Algorithmic_Train/Shared_Nodes"
