# Data
multitask: True
intermediate_functions_1: [["a_mod_29", 1, 3], ["b_mod_31", 1, 3]]
intermediate_functions_2: [["a_mod_29", 1, 2], ["b_mod_23", 1, 2]]
task_1_auxiliary_functions: [["b_mod_23", 1, 2]]
task_1_counterfactual_label_functions: [
  ["var_0", "counter_var_1", "+"],
  ["counter_var_0", "var_1", "+"],

]
task_2_auxiliary_functions: [["b_mod_31", 1, 3]]
task_2_counterfactual_label_functions: [
  ["var_0", "counter_var_1", "+"],
  ["counter_var_0", "var_1", "+"],
]
mod: 113
train_frac: .6
data_seed: 0

# Model
n_layer: 1
n_head: 4
n_embd: 128
n_inner: 512
n_positions: 5

# Training
lr_list: [.001]
model_seed_list: [0]
wd: 1.
betas: [0.9, 0.98]
num_epochs: 10000
checkpoint_every: 1000
save_checkpoints: [10000]
transfer: False

# Output
data_dir: "../data/Shared_Nodes"
save_models: True
model_dir: "../Model/Algorithmic_Train/Shared_Nodes"
results_dir: "../Results/Algorithmic_Train/Shared_Nodes"
figtitle: "Multitask"