batch_size_list:
- 500
data_seed: 0
gif: true
gif_interval: 10
l0_lambda: 1.0e-06
layer_reinit: false
lm_eval: true
lr_list:
- 0.001
mask_init_list:
- 0.0
max_temp: 200
model_dir: ../Model/Probes/Grokking/circuit_probing/b2/5000
model_path: ../Model/Algorithmic_Train/Grokking/model_LR_0.001_Seed_0_5000
model_seed_list:
- 0
num_epochs: 90
num_random_ablations: 0
operation_list:
- attn
- mlp
probe_index_list:
- 2
random_init: false
results_dir: ../Results/Probes/Grokking/circuit_probing/b2/5000
save_models: false
target_layer_list:
- 0
task: grokking
test_data_path: ../data/Grokking/test.csv
train_data_path: ../data/Grokking/train.csv
train_size: 2500
variable: aux_0
