# Model
model_type: "gpt_neox"
model_path: "EleutherAI/pythia-160m"
random_init: False
reinit_embeddings: False
layer_reinit: True
target_layer_list: [0, 1, 2, 3, 4, 5]
operation_list: ["attn", "mlp"]
mask_unit: "weight"
mask_init_list: [0.0]
max_temp: 200

# Data
train_data_path: "../data/ud-treebanks-conll2017/UD_English/en-ud-train.conllu"
lm_data_path: "../data/ud-treebanks-conll2017/UD_English/en-ud-dev.conllu"
label: "dep"
train_size: 1000
dev_size: 100
test_size: 1000
lm_size: 100

# Training
num_epochs: 90
lr_list: [0.001]
batch_size_list: [16]
data_seed: 0
model_seed_list: [0, 1, 2]
l0_lambda: 0.0000001

num_random_ablations: 1
lm_eval: True

# Output
model_dir: "../Models/"
results_dir: "../Results/Weight/Pythia160M/Dep/rand-layer-dep"
save_models: False