# Model
model_path: "../Model/Algorithmic_Train/Two_Nodes/amod29_bmod31/b2793434-2414-488c-bf83-33afed4b7df0"
random_init: False
layer_reinit: False
target_layer_list: [0]
operation_list: ["attn", "mlp"]
mask_init_list: [0.0]
max_temp: 200

# Data
train_data_path: "../data/Two_Nodes/amod29_bmod31/train.csv"
test_data_path: "../data/Two_Nodes/amod29_bmod31/test.csv"
variable: "var_0"
probe_index_list: [2]
train_size: 3000
multitask: False
agreement: False

# Training
num_epochs: 90
lr_list: [0.001]
batch_size_list: [500]
data_seed: 0
model_seed_list: [0]
l0_lambda: 0.000001

num_random_ablations: 0
lm_eval: True

# Output
model_dir: "../Model/Probes/Two_Nodes/amod29_bmod31/A/Mask/"
results_dir: "../Results/Probes/Two_Nodes/amod29_bmod31/A/Mask/"
save_models: True

# GIF
gif: True
gif_interval: 10